Calendar
lessuk400/Order pull request #3
Opened 2018-05-22 10:12 UTC by lessuk400

2018-05-22 10:43 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +$(document).ready ->
`$ ->`
coffee shortcut

2018-05-22 11:36 UTC, ailecksandr requested changes
Keep going

2018-05-22 11:36 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +$(document).ready ->
`$ ->`
coffee shortcut

2018-05-22 11:36 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +  $("#js_main").on "change", $("#js_food_item"),  ->
`.on 'change', '#js-food-item', ->`

prefer cebab-case here and you can omit jQuery

2018-05-22 11:36 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +      $(".js_food_item_price").last().val($(".js_food_item :selected").last().data("price"));
assign complex operations to separate variable or even move to separate method

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/application_controller.rb
> +  before_action :configure_permitted_parameters, if: :devise_controller?
no, I've meant you need to move that to your own `registrations` controller inherited from devise

[source](https://gist.github.com/kinopyo/2343176)

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/application_controller.rb
> +    redirect_to(request.referrer || root_path)
```ruby
redirect_to ..., alert: 'You are not admin of this lunch.'
```
[source](https://apidock.com/rails/ActionController/Base/redirect_to)

and move string to locales
[source](http://guides.rubyonrails.org/i18n.html)

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/application_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
call macroses right after module `inclusion/extension`

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/application_controller.rb
> +  def configure_permitted_parameters
you can override separate `sign_up/account_update` methods for this case as far as I remember.
Also move them to your overrided `registrations` controller

Just look here
[source](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L139)

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/food_items_controller.rb
> +    @food_item = FoodItem.create(food_items_params)
add space between assignation and `render/redirect`

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    authorize @menus
`authorize` before action. You have to check first if you have permissions to do something and then act

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    authorize @facade.menu
same in all places

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    if Date.today.saturday? || Date.today.sunday?
- assign facade above
- define necessary methods in facade
- define all redirect cases with guard clauses, e.g. `redirect_to root_path, alert: t('menus.new.messages.weekend')`

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    @menu = Menu.new menus_params
parentheses

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    if @menu.save
guard clause

[source](https://github.com/bbatsov/ruby-style-guide#no-nested-conditionals)

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +      meals_attributes: %i[price food_item_id _destroy])
indentation looks weird

FYI: you may find [this source](https://github.com/bbatsov/ruby-style-guide#no-double-indent) useful

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/orders_controller.rb
> +    @order = Order.new order_params
parentheses

[source](https://github.com/bbatsov/ruby-style-guide#method-invocation-parens)

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/orders_controller.rb
> +    @order.user_id = current_user.id
move all business logic to `operations/orders/create.rb` => `Orders::Create`

*Hint:* `order_params.merge(user_id: user.id)` in those operation will give the necessary params with user included

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/orders_controller.rb
> +      render plain: 'Da zaebalo'
locales and fix message

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/orders_controller.rb
> +    if @order.save
guard clause

2018-05-22 11:36 UTC, ailecksandr commented on app/controllers/orders_controller.rb
> +      .permit(order_meals_attributes: [:meal_id])
`%i[meal_id]`

2018-05-22 11:36 UTC, ailecksandr commented on app/helpers/menus_helper.rb
> +    'Hello. You should log in in our system'
add space after guard clauses

2018-05-22 11:36 UTC, ailecksandr commented on app/helpers/menus_helper.rb
> +    return 'You are admin of menu' if !current_user.nil? && current_user.has_role?(:admin)
`current_user&.has_role?(:admin)`

[source](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

+ locales

2018-05-22 11:36 UTC, ailecksandr commented on app/helpers/menus_helper.rb
> +  def user_role_status current_user
parentheses

[source](https://github.com/bbatsov/ruby-style-guide#method-parens)

2018-05-22 11:36 UTC, ailecksandr commented on app/models/menu.rb
> +    date # #Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
`an attribute` and what actually is that?

2018-05-22 11:36 UTC, ailecksandr commented on app/models/user.rb
> +    add_role :customer
what if plain user will not have roles at all? No role - no permissions )

2018-05-22 11:36 UTC, ailecksandr commented on app/models/user.rb
> +  def set_role
name it like `set_admin!`

2018-05-22 11:36 UTC, ailecksandr commented on app/models/user.rb
> +  before_create :set_role
`before_create :set_admin!, unless: -> { self.class.exists? }`

2018-05-22 11:36 UTC, ailecksandr commented on app/models/user.rb
> +    add_role :admin unless self.class.exists?
condition can be omitted

2018-05-22 11:36 UTC, ailecksandr commented on app/views/menus/new.html.erb
> +              <%= simple_form_for @facade.menu, html: { id: "myForm" } do |f| %>
be conventional. Go with `camelCase` id/classes namings or `kebab-case`. But not `snake_case`

2018-05-22 11:36 UTC, ailecksandr commented on app/views/menus/new.html.erb
> +                  <%= f.button :button, :id => "button_to_add_menu_item", type: "button" do %>
`..., id: 'blah-blah'`

2018-05-22 11:36 UTC, ailecksandr commented on app/views/menus/new.html.erb
> +      <% FoodItem.meal_types do |key,value| %>
`|key, value|` - space after comma

2018-05-22 11:36 UTC, ailecksandr commented on app/views/orders/index.html.erb
> +  <% order.order_meals.each do |om| %>
name it normally, not `om`

2018-05-22 11:36 UTC, ailecksandr commented on config/initializers/devise.rb
> +  config.secret_key = '0a37102ea08449d2150786350d49ccac0a135ddd'\
Use environment variables. You can try gem `dotenv` for this. That's very sensitive key

2018-05-22 11:36 UTC, ailecksandr commented on elect
> +=> [[32m#<Meal:0x00000000058ce808[0m
what a heck is that? )

move `public/uploads` => `.gitinore` to avoid adding your uploaded test files to repository

2018-05-25 07:24 UTC, ailecksandr commented on .env
> +SECRET_KEY = 0a37102ea08449d2150786350d49ccac0a135dddde5dd7e2999b5e2681d1a61a58fe3c3b444980099272c6f3da504f3a7e3fee0df07dd0f0d90c85e1e6440613
add file to `.gitignore`

2018-05-25 07:49 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +$ ->
you can even wrap that all in class. That's one of main advantages of Coffeescript

it'll be +- something like:
```
class OrderForm
  FOOD_ITEM_SELECTOR = '.js-food-item'

  constructor: (form) ->
    @form = $(form)

  init: ->
    @bindEvents()

  bindEvents: ->
    @form.on 'change', @FOOD_ITEM_SELECTOR, ->
      let price = $("#{@FOOD_ITEM_SELECTOR}:selected").data('price')

      this.attr('min', price).val(price)

$ ->
  new OrderForm('#js_main').init()

```
[source](https://coffeescript.org)

2018-05-25 07:50 UTC, ailecksandr commented on app/assets/stylesheets/hello.scss
> +// Place all the styles related to the Hello controller here.
remove unnecessary `scss` files

2018-05-25 07:51 UTC, ailecksandr commented on app/controllers/application_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
space between macros and module inslusion

2018-05-25 07:53 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    authorize Menus::NewFacade.new.menu
`authorize Menu`

2018-05-25 07:53 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    @menus = Menu.all
`authorize Menu`

2018-05-25 07:54 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    redirect_to root_path, flash: {warning: t('menus_messages.new.messages.weekends')} if
move `redirect_to root_path, flash ...` to private methods and call them here. Two-line ifs look messy

2018-05-25 07:55 UTC, ailecksandr commented on app/controllers/menus_controller.rb
> +    redirect_to menus_path and return if @menu.save
space below & above

`return redirect_to menus_path if @menu.save`

2018-05-25 07:56 UTC, ailecksandr commented on app/controllers/orders_controller.rb
> +    redirect_to orders_path and return if @order.save
space below & above

`return redirect_to ...`

2018-05-25 07:56 UTC, ailecksandr commented on app/controllers/orders_controller.rb
> +    params
you can take it all in one line here

2018-05-25 08:00 UTC, ailecksandr commented on app/controllers/users/registrations_controller.rb
> +    devise_parameter_sanitizer.permit(:sign_up) do |u|
move these two configurations to separate methods and call here

2018-05-25 08:01 UTC, ailecksandr commented on app/decorators/order_meal_decorator.rb
> +      .map { |obj| [obj.food_item.name, obj.id] }
`pluck('food_items.name, meals.id')` instead of `map`

2018-05-25 08:03 UTC, ailecksandr commented on app/helpers/menus_helper.rb
> +  # TODO: read about pundit
You've already read :)

2018-05-25 08:03 UTC, ailecksandr commented on app/helpers/menus_helper.rb
> +    return t('menus_messages.new.helpers.admin') if current_user&.has_role? :admin
current_user.admin?

2018-05-25 08:05 UTC, ailecksandr commented on app/helpers/menus_helper.rb
> +    return t('menus_messages.new.helpers.customer') unless current_user.nil?
`if current_user`

2018-05-25 08:06 UTC, ailecksandr commented on app/models/menu.rb
> +  def start_time
You should remove this as I remember, isn't it?

2018-05-25 08:07 UTC, ailecksandr commented on app/models/role.rb
> +  def is_admin?
can be omitted

2018-05-25 08:09 UTC, ailecksandr commented on app/policies/menu_policy.rb
> +    user&.has_role? :admin
`user&.admin?`

2018-05-25 08:10 UTC, ailecksandr commented on app/views/meals/index.html.erb
> +  <%= puts meal.foodItem.price %>
remove `puts`

2018-05-25 08:10 UTC, ailecksandr commented on elect
> +=> [[32m#<Meal:0x00000000058ce808[0m
remove file

2018-05-25 08:13 UTC, ailecksandr requested changes
Excellent work. Small fixes and we're all set to go

Also, please:
- rename commit about "Grobana forma"
- remove all git-ignored files from remote commits

2018-05-25 11:28 UTC, ailecksandr commented on app/assets/javascripts/food_items.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
remove unnecessary `coffee` files

2018-05-25 11:29 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +    console.log("#{@form}")
`console.log` can be omitted

2018-05-25 11:34 UTC, andrewr224 commented on app/controllers/menus_controller.rb
> +    authorize Menu
Add empty line after `authorize`

2018-05-25 11:35 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +    @form = $(FORM_SELECTOR)
```
constructor: (selector = FORM_SELECTOR) ->
  @form = $(selector)
...
```

2018-05-25 11:37 UTC, andrewr224 commented on app/controllers/menus_controller.rb
> +    redirect_to root_path, flash: {
[redirect_to doesn't stop the execution of the function](http://api.rubyonrails.org/classes/ActionController/Redirecting.html)

You need to add `return` to `redirect`

2018-05-25 11:37 UTC, andrewr224 commented on app/controllers/menus_controller.rb
> +    redirect_to root_path, flash: {
Same as above

2018-05-25 11:50 UTC, ailecksandr commented on app/assets/javascripts/script.coffee
> +class OrderForm
fix it as has been shown

2018-05-25 11:51 UTC, andrewr224 commented on app/models/food_item.rb
> +  validates :description, presence: true, length: { maximum: 100, minimum: 10 }
Align validations

2018-05-25 11:51 UTC, andrewr224 commented on app/policies/application_policy.rb
> +  def edit?
Make an alias

2018-05-25 11:51 UTC, andrewr224 commented on app/policies/application_policy.rb
> +  def new?
Make an alias

2018-05-25 14:38 UTC, closed without merging